version: '3.4'

services:
  mediscreen.sqlserverdatabase:
    container_name: mediscreen.sqlserverdatabase
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd!
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - 8001:1433

  mediscreen.mongodbclient:
    container_name: mediscreen.mongodbclient
    image: mongo
    secrets:
      - mongodb_connection_string
    environment:
      - ConnectionStrings__MongoDb_FILE=/run/secrets/mongodb_connection_string
    volumes:
      - mongodb_data:/mongo/data:/data/db
    ports:
      - 27017:27017

  mediscreen.cache:
    container_name: mediscreen.cache
    image: redis:7.2.5
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - mediscreen.sqlserverdatabase

  mediscreen.api:
    container_name: mediscreen.api
    image: ${DOCKER_REGISTRY-}mediscreenapi
    build:
      context: .
      dockerfile: Mediscreen.API/Dockerfile
    ports:
      - 65255:80
      - 65256:443
    depends_on:
      - mediscreen.sqlserverdatabase
      - mediscreen.mongodbclient
      - mediscreen.cache

  mediscreen.ui:
    container_name: mediscreen.ui
    image: ${DOCKER_REGISTRY-}mediscreenui
    build:
      context: .
      dockerfile: Mediscreen.UI/Dockerfile
    ports:
      - 65258:80
      - 65257:443
    depends_on:
      - mediscreen.api

secrets:
  mongodb_connection_string:
    external: true

volumes:
  sqlserver_data:
  mongodb_data:

  