// <auto-generated />
using System;
using Mediscreen.Infrastructure.SqlServerDatabase.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mediscreen.Infrastructure.SqlServerDatabase.Migrations
{
    [DbContext(typeof(MediscreenSqlServerContext))]
    [Migration("20240531145547_AddPatientSeedData")]
    partial class AddPatientSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mediscreen.Infrastructure.SqlServerDatabase.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 249,
                            BirthDate = new DateTime(2010, 7, 11, 9, 47, 57, 378, DateTimeKind.Local).AddTicks(5170),
                            FirstName = "Bernita",
                            Gender = "F",
                            HomeAddress = "0239 Bradtke Port, Madelynnburgh, Nauru",
                            LastName = "Konopelski",
                            PhoneNumber = "1-701-937-1738 x8576"
                        },
                        new
                        {
                            Id = 772,
                            BirthDate = new DateTime(2006, 9, 7, 0, 30, 17, 371, DateTimeKind.Local).AddTicks(7370),
                            FirstName = "Guillermo",
                            Gender = "M",
                            HomeAddress = "700 Dane Branch, Georgianaburgh, Philippines",
                            LastName = "Cummerata",
                            PhoneNumber = "703-237-8869"
                        },
                        new
                        {
                            Id = 294,
                            BirthDate = new DateTime(2020, 11, 3, 15, 12, 37, 364, DateTimeKind.Local).AddTicks(7944),
                            FirstName = "Max",
                            Gender = "F",
                            HomeAddress = "58600 Heidenreich Isle, Casperhaven, Saint Martin",
                            LastName = "Streich",
                            PhoneNumber = "(340) 694-5534 x225"
                        },
                        new
                        {
                            Id = 816,
                            BirthDate = new DateTime(2016, 12, 31, 5, 54, 57, 357, DateTimeKind.Local).AddTicks(8553),
                            FirstName = "Yoshiko",
                            Gender = "M",
                            HomeAddress = "253 Jany Shoals, Oswaldomouth, Mali",
                            LastName = "Maggio",
                            PhoneNumber = "(838) 864-0031 x636"
                        },
                        new
                        {
                            Id = 339,
                            BirthDate = new DateTime(2013, 2, 26, 20, 37, 17, 350, DateTimeKind.Local).AddTicks(9087),
                            FirstName = "Edd",
                            Gender = "M",
                            HomeAddress = "93004 Mertz Cove, Port Austenfort, Egypt",
                            LastName = "Gislason",
                            PhoneNumber = "(271) 872-7910 x731"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
